name: Python CI

on:
  push:
    branches:
      - main  # Trigger the CI on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the CI on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the environment to run the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up the specified version of Python
      with:
        python-version: 3.9  # You can specify any version here (e.g., 3.8, 3.9, etc.)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        pip install random 

    - name: Run tests
      run: |
        python test_game.py
